/* This file is generated by genstat. */
/* No manual modification is permitted. */

package com.netease.game.stat;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

  
// ddzserver统计结构
public class DdzStatMgr
{
	private static DdzStatMgr instance;
	
    
    // 桌子数目
    private int TotalTableNum;
    
    // 桌子上的玩家数目
    private int TotalPlayerNum;
    
    // fps数目
    private int TotalFPS;
    
    // 开局的桌子
    private int NewTableNum;
    
    // 结算的桌子
    private int DestroyTableNum;
    
    // 异常的桌子
    private int ExceptionTableNum;
    
    // 收包数目
    private int RecvPacketNum;
    
    // 发包数目
    private int SendPacketNum;
    
    // 收包流量
    private int RecvSizeNum;
    
    // 发包流量
    private int SendSizeNum;
    
    // Top收包处理时间
    private int ProcessTime;
    
    
    // 各个线程的桌子数目
    private int[] TableNum = new int[100];
    
    // 各个房间的桌子数目
    private int[] RoomTableNum = new int[3];
    
    // 各个线程的玩家数目
    private int[] PlayerNum = new int[100];
    
    // 各个线程的fps数目
    private int[] FPS = new int[100];
    
    // 桌子各状态数目
    private int[] RoutineStateNum = new int[11];
    
    
    // Top收包数目
    private int[] TopRecvPacketNum = new int[50];
    
    // Top发包数目
    private int[] TopSendPacketNum = new int[50];
    
    // Top收包流量
    private int[] TopRecvSizeNum = new int[50];
    
    // Top发包流量
    private int[] TopSendSizeNum = new int[50];
    
    // Top收包处理时间
    private int[] TopProcessTime = new int[50];
        
        
	
	// ddzserver统计结构
    public DdzStatMgr()
	{
		clear();
	}
	
	public static DdzStatMgr instance()
	{
		if (instance == null)
		{
			synchronized (DdzStatMgr.class)
			{
				if (instance == null)
				{
					instance = new DdzStatMgr();
					return instance;
				}
			}
		}
		return instance;
	}
	
	public void sortArray(int[] src, int[] desId, int[] desVal, boolean isMax)
	{
		int srcSize = src.length;
		int desSize = desId.length;
		if (isMax)
		{
			for (int i = 0; i < desSize; i++)
			{
				desId[i] = 0;
				desVal[i] = 0;
				int max = 0;
				for (int j = 0; j < srcSize; j++)
				{
					if (src[j] > max)
					{
						desId[i] = j;
						desVal[i] = src[j];
						max = src[j];
					}
				}
				src[desId[i]] = 0;
			}
		}
		else
		{
			for (int i = 0; i < desSize; i++)
			{
				desId[i] = 0;
				desVal[i] = 0;
				int min = 0xFFFFFFFF;
				for (int j = 0; j < srcSize; j++)
				{
					if (src[j] < min && src[j] > 0)
					{
						desId[i] = j;
						desVal[i] = src[j];
						min = src[j];
					}
				}
				src[desId[i]] = 0xFFFFFFFF;
			}
		}
	}

	public void sortHashMap(ConcurrentHashMap<Integer, Integer> map, int[] desId, int[] desVal, boolean isMax)
	{
		int desSize = desId.length;
		if (isMax)
		{
			for (int i = 0; i < desSize; i++)
			{
				desId[i] = 0;
				desVal[i] = 0;
				int max = 0;
				for (Map.Entry<Integer, Integer> e : map.entrySet())
				{
					if (e.getValue() > max)
					{
						desId[i] = e.getKey();
						desVal[i] = e.getValue();
						max = e.getValue();
					}
				}
				if (map.containsKey(desId[i]))
				{
					map.put(desId[i], 0);
				}
			}
		}
		else
		{
			for (int i = 0; i < desSize; i++)
			{
				desId[i] = 0;
				desVal[i] = 0;
				int min = 0xFFFFFFFF;
				for (Map.Entry<Integer, Integer> e : map.entrySet())
				{
					if (e.getValue() < min && e.getValue() > 0)
					{
						desId[i] = e.getKey();
						desVal[i] = e.getValue();
						min = e.getValue();
					}
				}
				if (map.containsKey(desId[i]))
				{
					map.put(desId[i], 0);
				}
			}
		}
	}
		
    
    // get 桌子数目
    public int getTotalTableNum()
    {
        return TotalTableNum;
    }
    
    // set 桌子数目
    public void setTotalTableNum(int _TotalTableNum)
    {
        TotalTableNum = _TotalTableNum;
    }
    
    // add 桌子数目
    public void addTotalTableNum(int _TotalTableNum)
    {
        TotalTableNum += _TotalTableNum;
    }
    
    // get 桌子上的玩家数目
    public int getTotalPlayerNum()
    {
        return TotalPlayerNum;
    }
    
    // set 桌子上的玩家数目
    public void setTotalPlayerNum(int _TotalPlayerNum)
    {
        TotalPlayerNum = _TotalPlayerNum;
    }
    
    // add 桌子上的玩家数目
    public void addTotalPlayerNum(int _TotalPlayerNum)
    {
        TotalPlayerNum += _TotalPlayerNum;
    }
    
    // get fps数目
    public int getTotalFPS()
    {
        return TotalFPS;
    }
    
    // set fps数目
    public void setTotalFPS(int _TotalFPS)
    {
        TotalFPS = _TotalFPS;
    }
    
    // add fps数目
    public void addTotalFPS(int _TotalFPS)
    {
        TotalFPS += _TotalFPS;
    }
    
    // get 开局的桌子
    public int getNewTableNum()
    {
        return NewTableNum;
    }
    
    // set 开局的桌子
    public void setNewTableNum(int _NewTableNum)
    {
        NewTableNum = _NewTableNum;
    }
    
    // add 开局的桌子
    public void addNewTableNum(int _NewTableNum)
    {
        NewTableNum += _NewTableNum;
    }
    
    // get 结算的桌子
    public int getDestroyTableNum()
    {
        return DestroyTableNum;
    }
    
    // set 结算的桌子
    public void setDestroyTableNum(int _DestroyTableNum)
    {
        DestroyTableNum = _DestroyTableNum;
    }
    
    // add 结算的桌子
    public void addDestroyTableNum(int _DestroyTableNum)
    {
        DestroyTableNum += _DestroyTableNum;
    }
    
    // get 异常的桌子
    public int getExceptionTableNum()
    {
        return ExceptionTableNum;
    }
    
    // set 异常的桌子
    public void setExceptionTableNum(int _ExceptionTableNum)
    {
        ExceptionTableNum = _ExceptionTableNum;
    }
    
    // add 异常的桌子
    public void addExceptionTableNum(int _ExceptionTableNum)
    {
        ExceptionTableNum += _ExceptionTableNum;
    }
    
    // get 收包数目
    public int getRecvPacketNum()
    {
        return RecvPacketNum;
    }
    
    // set 收包数目
    public void setRecvPacketNum(int _RecvPacketNum)
    {
        RecvPacketNum = _RecvPacketNum;
    }
    
    // add 收包数目
    public void addRecvPacketNum(int _RecvPacketNum)
    {
        RecvPacketNum += _RecvPacketNum;
    }
    
    // get 发包数目
    public int getSendPacketNum()
    {
        return SendPacketNum;
    }
    
    // set 发包数目
    public void setSendPacketNum(int _SendPacketNum)
    {
        SendPacketNum = _SendPacketNum;
    }
    
    // add 发包数目
    public void addSendPacketNum(int _SendPacketNum)
    {
        SendPacketNum += _SendPacketNum;
    }
    
    // get 收包流量
    public int getRecvSizeNum()
    {
        return RecvSizeNum;
    }
    
    // set 收包流量
    public void setRecvSizeNum(int _RecvSizeNum)
    {
        RecvSizeNum = _RecvSizeNum;
    }
    
    // add 收包流量
    public void addRecvSizeNum(int _RecvSizeNum)
    {
        RecvSizeNum += _RecvSizeNum;
    }
    
    // get 发包流量
    public int getSendSizeNum()
    {
        return SendSizeNum;
    }
    
    // set 发包流量
    public void setSendSizeNum(int _SendSizeNum)
    {
        SendSizeNum = _SendSizeNum;
    }
    
    // add 发包流量
    public void addSendSizeNum(int _SendSizeNum)
    {
        SendSizeNum += _SendSizeNum;
    }
    
    // get Top收包处理时间
    public int getProcessTime()
    {
        return ProcessTime;
    }
    
    // set Top收包处理时间
    public void setProcessTime(int _ProcessTime)
    {
        ProcessTime = _ProcessTime;
    }
    
    // add Top收包处理时间
    public void addProcessTime(int _ProcessTime)
    {
        ProcessTime += _ProcessTime;
    }
    
    
         
	// set 各个线程的桌子数目
    public void setTableNum(int index, int _TableNum)
    {
		if (index >= 100)
        {
            return;
        }
        TableNum[index] += _TableNum;
    }
	
    // add 各个线程的桌子数目
    public void addTableNum(int index, int _TableNum)
    {
        if (index >= 100)
        {
            return;
        }
        TableNum[index] += _TableNum;
    }
         
	// set 各个房间的桌子数目
    public void setRoomTableNum(int index, int _RoomTableNum)
    {
		if (index >= 3)
        {
            return;
        }
        RoomTableNum[index] += _RoomTableNum;
    }
	
    // add 各个房间的桌子数目
    public void addRoomTableNum(int index, int _RoomTableNum)
    {
        if (index >= 3)
        {
            return;
        }
        RoomTableNum[index] += _RoomTableNum;
    }
         
	// set 各个线程的玩家数目
    public void setPlayerNum(int index, int _PlayerNum)
    {
		if (index >= 100)
        {
            return;
        }
        PlayerNum[index] += _PlayerNum;
    }
	
    // add 各个线程的玩家数目
    public void addPlayerNum(int index, int _PlayerNum)
    {
        if (index >= 100)
        {
            return;
        }
        PlayerNum[index] += _PlayerNum;
    }
         
	// set 各个线程的fps数目
    public void setFPS(int index, int _FPS)
    {
		if (index >= 100)
        {
            return;
        }
        FPS[index] += _FPS;
    }
	
    // add 各个线程的fps数目
    public void addFPS(int index, int _FPS)
    {
        if (index >= 100)
        {
            return;
        }
        FPS[index] += _FPS;
    }
         
	// set 桌子各状态数目
    public void setRoutineStateNum(int index, int _RoutineStateNum)
    {
		if (index >= 11)
        {
            return;
        }
        RoutineStateNum[index] += _RoutineStateNum;
    }
	
    // add 桌子各状态数目
    public void addRoutineStateNum(int index, int _RoutineStateNum)
    {
        if (index >= 11)
        {
            return;
        }
        RoutineStateNum[index] += _RoutineStateNum;
    }
    
	
          
	// set Top收包数目
    public void setTopRecvPacketNum(int index, int _TopRecvPacketNum)
    {
		if (index >= 50)
        {
            return;
        }
        TopRecvPacketNum[index] += _TopRecvPacketNum;
    }
	       
    // add Top收包数目
    public void addTopRecvPacketNum(int index, int _TopRecvPacketNum)
    {
        if (index >= 50)
        {
            return;
        }
        TopRecvPacketNum[index] += _TopRecvPacketNum;
    }
          
	// set Top发包数目
    public void setTopSendPacketNum(int index, int _TopSendPacketNum)
    {
		if (index >= 50)
        {
            return;
        }
        TopSendPacketNum[index] += _TopSendPacketNum;
    }
	       
    // add Top发包数目
    public void addTopSendPacketNum(int index, int _TopSendPacketNum)
    {
        if (index >= 50)
        {
            return;
        }
        TopSendPacketNum[index] += _TopSendPacketNum;
    }
          
	// set Top收包流量
    public void setTopRecvSizeNum(int index, int _TopRecvSizeNum)
    {
		if (index >= 50)
        {
            return;
        }
        TopRecvSizeNum[index] += _TopRecvSizeNum;
    }
	       
    // add Top收包流量
    public void addTopRecvSizeNum(int index, int _TopRecvSizeNum)
    {
        if (index >= 50)
        {
            return;
        }
        TopRecvSizeNum[index] += _TopRecvSizeNum;
    }
          
	// set Top发包流量
    public void setTopSendSizeNum(int index, int _TopSendSizeNum)
    {
		if (index >= 50)
        {
            return;
        }
        TopSendSizeNum[index] += _TopSendSizeNum;
    }
	       
    // add Top发包流量
    public void addTopSendSizeNum(int index, int _TopSendSizeNum)
    {
        if (index >= 50)
        {
            return;
        }
        TopSendSizeNum[index] += _TopSendSizeNum;
    }
          
	// set Top收包处理时间
    public void setTopProcessTime(int index, int _TopProcessTime)
    {
		if (index >= 50)
        {
            return;
        }
        TopProcessTime[index] += _TopProcessTime;
    }
	       
    // add Top收包处理时间
    public void addTopProcessTime(int index, int _TopProcessTime)
    {
        if (index >= 50)
        {
            return;
        }
        TopProcessTime[index] += _TopProcessTime;
    }
    
	
    
    
    public void clear()
	{
		
		// 桌子数目
		TotalTableNum = 0;
		
		// 桌子上的玩家数目
		TotalPlayerNum = 0;
		
		// fps数目
		TotalFPS = 0;
		
		// 开局的桌子
		NewTableNum = 0;
		
		// 结算的桌子
		DestroyTableNum = 0;
		
		// 异常的桌子
		ExceptionTableNum = 0;
		
		// 收包数目
		RecvPacketNum = 0;
		
		// 发包数目
		SendPacketNum = 0;
		
		// 收包流量
		RecvSizeNum = 0;
		
		// 发包流量
		SendSizeNum = 0;
		
		// Top收包处理时间
		ProcessTime = 0;
		
		
		// 各个线程的桌子数目
		for (int i = 0; i < TableNum.length; i++)
		{
			TableNum[i] = 0;
		}
		
		// 各个房间的桌子数目
		for (int i = 0; i < RoomTableNum.length; i++)
		{
			RoomTableNum[i] = 0;
		}
		
		// 各个线程的玩家数目
		for (int i = 0; i < PlayerNum.length; i++)
		{
			PlayerNum[i] = 0;
		}
		
		// 各个线程的fps数目
		for (int i = 0; i < FPS.length; i++)
		{
			FPS[i] = 0;
		}
		
		// 桌子各状态数目
		for (int i = 0; i < RoutineStateNum.length; i++)
		{
			RoutineStateNum[i] = 0;
		}
		
		
		// Top收包数目
		for (int i = 0; i < TopRecvPacketNum.length; i++)
		{
			TopRecvPacketNum[i] = 0;
		}
		
		// Top发包数目
		for (int i = 0; i < TopSendPacketNum.length; i++)
		{
			TopSendPacketNum[i] = 0;
		}
		
		// Top收包流量
		for (int i = 0; i < TopRecvSizeNum.length; i++)
		{
			TopRecvSizeNum[i] = 0;
		}
		
		// Top发包流量
		for (int i = 0; i < TopSendSizeNum.length; i++)
		{
			TopSendSizeNum[i] = 0;
		}
		
		// Top收包处理时间
		for (int i = 0; i < TopProcessTime.length; i++)
		{
			TopProcessTime[i] = 0;
		}
		
		
	}

    public void printLog(String strFile)
	{
		File file = null;
		try
		{
			file = new File("log/");
			if (!file.exists())
			{
				file.mkdirs();
			}
			file = new File("log/" + strFile);
			if (!file.exists())
			{
				file.createNewFile();
			}
		}
		catch (IOException e)
		{
			e.printStackTrace();
			return;
		}
		
		Date date = new Date();
		DateFormat format = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
		String time = format.format(date);

		
		// Top收包数目
		int[] uTopRecvPacketNumId = new int[5];
		int[] uTopRecvPacketNumVal = new int[5];
		sortArray(TopRecvPacketNum, uTopRecvPacketNumId, uTopRecvPacketNumVal, true);
		
		// Top发包数目
		int[] uTopSendPacketNumId = new int[5];
		int[] uTopSendPacketNumVal = new int[5];
		sortArray(TopSendPacketNum, uTopSendPacketNumId, uTopSendPacketNumVal, true);
		
		// Top收包流量
		int[] uTopRecvSizeNumId = new int[5];
		int[] uTopRecvSizeNumVal = new int[5];
		sortArray(TopRecvSizeNum, uTopRecvSizeNumId, uTopRecvSizeNumVal, true);
		
		// Top发包流量
		int[] uTopSendSizeNumId = new int[5];
		int[] uTopSendSizeNumVal = new int[5];
		sortArray(TopSendSizeNum, uTopSendSizeNumId, uTopSendSizeNumVal, true);
		
		// Top收包处理时间
		int[] uTopProcessTimeId = new int[5];
		int[] uTopProcessTimeVal = new int[5];
		sortArray(TopProcessTime, uTopProcessTimeId, uTopProcessTimeVal, true);
		
		
		
		String str = String.format("=============================%s=============================\n" +
			
			// 桌子数目
			"TotalTableNum\t%d\t桌子数目\n" +
			
			// 桌子上的玩家数目
			"TotalPlayerNum\t%d\t桌子上的玩家数目\n" +
			
			// fps数目
			"TotalFPS\t%d\tfps数目\n" +
			
			// 开局的桌子
			"NewTableNum\t%d\t开局的桌子\n" +
			
			// 结算的桌子
			"DestroyTableNum\t%d\t结算的桌子\n" +
			
			// 异常的桌子
			"ExceptionTableNum\t%d\t异常的桌子\n" +
			
			// 收包数目
			"RecvPacketNum\t%d\t收包数目\n" +
			
			// 发包数目
			"SendPacketNum\t%d\t发包数目\n" +
			
			// 收包流量
			"RecvSizeNum\t%d\t收包流量\n" +
			
			// 发包流量
			"SendSizeNum\t%d\t发包流量\n" +
			
			// Top收包处理时间
			"ProcessTime\t%d\tTop收包处理时间\n" +
			
			
			
			// 各个线程的桌子数目 0
			"TableNum0\t%d\t各个线程的桌子数目0\n" +
			
			// 各个线程的桌子数目 1
			"TableNum1\t%d\t各个线程的桌子数目1\n" +
			
			// 各个线程的桌子数目 2
			"TableNum2\t%d\t各个线程的桌子数目2\n" +
			
			// 各个线程的桌子数目 3
			"TableNum3\t%d\t各个线程的桌子数目3\n" +
			
			// 各个线程的桌子数目 4
			"TableNum4\t%d\t各个线程的桌子数目4\n" +
			
			// 各个线程的桌子数目 5
			"TableNum5\t%d\t各个线程的桌子数目5\n" +
			
			// 各个线程的桌子数目 6
			"TableNum6\t%d\t各个线程的桌子数目6\n" +
			
			// 各个线程的桌子数目 7
			"TableNum7\t%d\t各个线程的桌子数目7\n" +
			
			// 各个线程的桌子数目 8
			"TableNum8\t%d\t各个线程的桌子数目8\n" +
			
			// 各个线程的桌子数目 9
			"TableNum9\t%d\t各个线程的桌子数目9\n" +
			
			// 各个线程的桌子数目 10
			"TableNum10\t%d\t各个线程的桌子数目10\n" +
			
			// 各个线程的桌子数目 11
			"TableNum11\t%d\t各个线程的桌子数目11\n" +
			
			// 各个线程的桌子数目 12
			"TableNum12\t%d\t各个线程的桌子数目12\n" +
			
			// 各个线程的桌子数目 13
			"TableNum13\t%d\t各个线程的桌子数目13\n" +
			
			// 各个线程的桌子数目 14
			"TableNum14\t%d\t各个线程的桌子数目14\n" +
			
			// 各个线程的桌子数目 15
			"TableNum15\t%d\t各个线程的桌子数目15\n" +
			
			// 各个线程的桌子数目 16
			"TableNum16\t%d\t各个线程的桌子数目16\n" +
			
			// 各个线程的桌子数目 17
			"TableNum17\t%d\t各个线程的桌子数目17\n" +
			
			// 各个线程的桌子数目 18
			"TableNum18\t%d\t各个线程的桌子数目18\n" +
			
			// 各个线程的桌子数目 19
			"TableNum19\t%d\t各个线程的桌子数目19\n" +
			
			// 各个线程的桌子数目 20
			"TableNum20\t%d\t各个线程的桌子数目20\n" +
			
			// 各个线程的桌子数目 21
			"TableNum21\t%d\t各个线程的桌子数目21\n" +
			
			// 各个线程的桌子数目 22
			"TableNum22\t%d\t各个线程的桌子数目22\n" +
			
			// 各个线程的桌子数目 23
			"TableNum23\t%d\t各个线程的桌子数目23\n" +
			
			// 各个线程的桌子数目 24
			"TableNum24\t%d\t各个线程的桌子数目24\n" +
			
			// 各个线程的桌子数目 25
			"TableNum25\t%d\t各个线程的桌子数目25\n" +
			
			// 各个线程的桌子数目 26
			"TableNum26\t%d\t各个线程的桌子数目26\n" +
			
			// 各个线程的桌子数目 27
			"TableNum27\t%d\t各个线程的桌子数目27\n" +
			
			// 各个线程的桌子数目 28
			"TableNum28\t%d\t各个线程的桌子数目28\n" +
			
			// 各个线程的桌子数目 29
			"TableNum29\t%d\t各个线程的桌子数目29\n" +
			
			// 各个线程的桌子数目 30
			"TableNum30\t%d\t各个线程的桌子数目30\n" +
			
			// 各个线程的桌子数目 31
			"TableNum31\t%d\t各个线程的桌子数目31\n" +
			
			// 各个线程的桌子数目 32
			"TableNum32\t%d\t各个线程的桌子数目32\n" +
			
			// 各个线程的桌子数目 33
			"TableNum33\t%d\t各个线程的桌子数目33\n" +
			
			// 各个线程的桌子数目 34
			"TableNum34\t%d\t各个线程的桌子数目34\n" +
			
			// 各个线程的桌子数目 35
			"TableNum35\t%d\t各个线程的桌子数目35\n" +
			
			// 各个线程的桌子数目 36
			"TableNum36\t%d\t各个线程的桌子数目36\n" +
			
			// 各个线程的桌子数目 37
			"TableNum37\t%d\t各个线程的桌子数目37\n" +
			
			// 各个线程的桌子数目 38
			"TableNum38\t%d\t各个线程的桌子数目38\n" +
			
			// 各个线程的桌子数目 39
			"TableNum39\t%d\t各个线程的桌子数目39\n" +
			
			// 各个线程的桌子数目 40
			"TableNum40\t%d\t各个线程的桌子数目40\n" +
			
			// 各个线程的桌子数目 41
			"TableNum41\t%d\t各个线程的桌子数目41\n" +
			
			// 各个线程的桌子数目 42
			"TableNum42\t%d\t各个线程的桌子数目42\n" +
			
			// 各个线程的桌子数目 43
			"TableNum43\t%d\t各个线程的桌子数目43\n" +
			
			// 各个线程的桌子数目 44
			"TableNum44\t%d\t各个线程的桌子数目44\n" +
			
			// 各个线程的桌子数目 45
			"TableNum45\t%d\t各个线程的桌子数目45\n" +
			
			// 各个线程的桌子数目 46
			"TableNum46\t%d\t各个线程的桌子数目46\n" +
			
			// 各个线程的桌子数目 47
			"TableNum47\t%d\t各个线程的桌子数目47\n" +
			
			// 各个线程的桌子数目 48
			"TableNum48\t%d\t各个线程的桌子数目48\n" +
			
			// 各个线程的桌子数目 49
			"TableNum49\t%d\t各个线程的桌子数目49\n" +
			
			// 各个线程的桌子数目 50
			"TableNum50\t%d\t各个线程的桌子数目50\n" +
			
			// 各个线程的桌子数目 51
			"TableNum51\t%d\t各个线程的桌子数目51\n" +
			
			// 各个线程的桌子数目 52
			"TableNum52\t%d\t各个线程的桌子数目52\n" +
			
			// 各个线程的桌子数目 53
			"TableNum53\t%d\t各个线程的桌子数目53\n" +
			
			// 各个线程的桌子数目 54
			"TableNum54\t%d\t各个线程的桌子数目54\n" +
			
			// 各个线程的桌子数目 55
			"TableNum55\t%d\t各个线程的桌子数目55\n" +
			
			// 各个线程的桌子数目 56
			"TableNum56\t%d\t各个线程的桌子数目56\n" +
			
			// 各个线程的桌子数目 57
			"TableNum57\t%d\t各个线程的桌子数目57\n" +
			
			// 各个线程的桌子数目 58
			"TableNum58\t%d\t各个线程的桌子数目58\n" +
			
			// 各个线程的桌子数目 59
			"TableNum59\t%d\t各个线程的桌子数目59\n" +
			
			// 各个线程的桌子数目 60
			"TableNum60\t%d\t各个线程的桌子数目60\n" +
			
			// 各个线程的桌子数目 61
			"TableNum61\t%d\t各个线程的桌子数目61\n" +
			
			// 各个线程的桌子数目 62
			"TableNum62\t%d\t各个线程的桌子数目62\n" +
			
			// 各个线程的桌子数目 63
			"TableNum63\t%d\t各个线程的桌子数目63\n" +
			
			// 各个线程的桌子数目 64
			"TableNum64\t%d\t各个线程的桌子数目64\n" +
			
			// 各个线程的桌子数目 65
			"TableNum65\t%d\t各个线程的桌子数目65\n" +
			
			// 各个线程的桌子数目 66
			"TableNum66\t%d\t各个线程的桌子数目66\n" +
			
			// 各个线程的桌子数目 67
			"TableNum67\t%d\t各个线程的桌子数目67\n" +
			
			// 各个线程的桌子数目 68
			"TableNum68\t%d\t各个线程的桌子数目68\n" +
			
			// 各个线程的桌子数目 69
			"TableNum69\t%d\t各个线程的桌子数目69\n" +
			
			// 各个线程的桌子数目 70
			"TableNum70\t%d\t各个线程的桌子数目70\n" +
			
			// 各个线程的桌子数目 71
			"TableNum71\t%d\t各个线程的桌子数目71\n" +
			
			// 各个线程的桌子数目 72
			"TableNum72\t%d\t各个线程的桌子数目72\n" +
			
			// 各个线程的桌子数目 73
			"TableNum73\t%d\t各个线程的桌子数目73\n" +
			
			// 各个线程的桌子数目 74
			"TableNum74\t%d\t各个线程的桌子数目74\n" +
			
			// 各个线程的桌子数目 75
			"TableNum75\t%d\t各个线程的桌子数目75\n" +
			
			// 各个线程的桌子数目 76
			"TableNum76\t%d\t各个线程的桌子数目76\n" +
			
			// 各个线程的桌子数目 77
			"TableNum77\t%d\t各个线程的桌子数目77\n" +
			
			// 各个线程的桌子数目 78
			"TableNum78\t%d\t各个线程的桌子数目78\n" +
			
			// 各个线程的桌子数目 79
			"TableNum79\t%d\t各个线程的桌子数目79\n" +
			
			// 各个线程的桌子数目 80
			"TableNum80\t%d\t各个线程的桌子数目80\n" +
			
			// 各个线程的桌子数目 81
			"TableNum81\t%d\t各个线程的桌子数目81\n" +
			
			// 各个线程的桌子数目 82
			"TableNum82\t%d\t各个线程的桌子数目82\n" +
			
			// 各个线程的桌子数目 83
			"TableNum83\t%d\t各个线程的桌子数目83\n" +
			
			// 各个线程的桌子数目 84
			"TableNum84\t%d\t各个线程的桌子数目84\n" +
			
			// 各个线程的桌子数目 85
			"TableNum85\t%d\t各个线程的桌子数目85\n" +
			
			// 各个线程的桌子数目 86
			"TableNum86\t%d\t各个线程的桌子数目86\n" +
			
			// 各个线程的桌子数目 87
			"TableNum87\t%d\t各个线程的桌子数目87\n" +
			
			// 各个线程的桌子数目 88
			"TableNum88\t%d\t各个线程的桌子数目88\n" +
			
			// 各个线程的桌子数目 89
			"TableNum89\t%d\t各个线程的桌子数目89\n" +
			
			// 各个线程的桌子数目 90
			"TableNum90\t%d\t各个线程的桌子数目90\n" +
			
			// 各个线程的桌子数目 91
			"TableNum91\t%d\t各个线程的桌子数目91\n" +
			
			// 各个线程的桌子数目 92
			"TableNum92\t%d\t各个线程的桌子数目92\n" +
			
			// 各个线程的桌子数目 93
			"TableNum93\t%d\t各个线程的桌子数目93\n" +
			
			// 各个线程的桌子数目 94
			"TableNum94\t%d\t各个线程的桌子数目94\n" +
			
			// 各个线程的桌子数目 95
			"TableNum95\t%d\t各个线程的桌子数目95\n" +
			
			// 各个线程的桌子数目 96
			"TableNum96\t%d\t各个线程的桌子数目96\n" +
			
			// 各个线程的桌子数目 97
			"TableNum97\t%d\t各个线程的桌子数目97\n" +
			
			// 各个线程的桌子数目 98
			"TableNum98\t%d\t各个线程的桌子数目98\n" +
			
			// 各个线程的桌子数目 99
			"TableNum99\t%d\t各个线程的桌子数目99\n" +
			
			
			
			// 各个房间的桌子数目 0
			"RoomTableNum0\t%d\t各个房间的桌子数目0\n" +
			
			// 各个房间的桌子数目 1
			"RoomTableNum1\t%d\t各个房间的桌子数目1\n" +
			
			// 各个房间的桌子数目 2
			"RoomTableNum2\t%d\t各个房间的桌子数目2\n" +
			
			
			
			// 各个线程的玩家数目 0
			"PlayerNum0\t%d\t各个线程的玩家数目0\n" +
			
			// 各个线程的玩家数目 1
			"PlayerNum1\t%d\t各个线程的玩家数目1\n" +
			
			// 各个线程的玩家数目 2
			"PlayerNum2\t%d\t各个线程的玩家数目2\n" +
			
			// 各个线程的玩家数目 3
			"PlayerNum3\t%d\t各个线程的玩家数目3\n" +
			
			// 各个线程的玩家数目 4
			"PlayerNum4\t%d\t各个线程的玩家数目4\n" +
			
			// 各个线程的玩家数目 5
			"PlayerNum5\t%d\t各个线程的玩家数目5\n" +
			
			// 各个线程的玩家数目 6
			"PlayerNum6\t%d\t各个线程的玩家数目6\n" +
			
			// 各个线程的玩家数目 7
			"PlayerNum7\t%d\t各个线程的玩家数目7\n" +
			
			// 各个线程的玩家数目 8
			"PlayerNum8\t%d\t各个线程的玩家数目8\n" +
			
			// 各个线程的玩家数目 9
			"PlayerNum9\t%d\t各个线程的玩家数目9\n" +
			
			// 各个线程的玩家数目 10
			"PlayerNum10\t%d\t各个线程的玩家数目10\n" +
			
			// 各个线程的玩家数目 11
			"PlayerNum11\t%d\t各个线程的玩家数目11\n" +
			
			// 各个线程的玩家数目 12
			"PlayerNum12\t%d\t各个线程的玩家数目12\n" +
			
			// 各个线程的玩家数目 13
			"PlayerNum13\t%d\t各个线程的玩家数目13\n" +
			
			// 各个线程的玩家数目 14
			"PlayerNum14\t%d\t各个线程的玩家数目14\n" +
			
			// 各个线程的玩家数目 15
			"PlayerNum15\t%d\t各个线程的玩家数目15\n" +
			
			// 各个线程的玩家数目 16
			"PlayerNum16\t%d\t各个线程的玩家数目16\n" +
			
			// 各个线程的玩家数目 17
			"PlayerNum17\t%d\t各个线程的玩家数目17\n" +
			
			// 各个线程的玩家数目 18
			"PlayerNum18\t%d\t各个线程的玩家数目18\n" +
			
			// 各个线程的玩家数目 19
			"PlayerNum19\t%d\t各个线程的玩家数目19\n" +
			
			// 各个线程的玩家数目 20
			"PlayerNum20\t%d\t各个线程的玩家数目20\n" +
			
			// 各个线程的玩家数目 21
			"PlayerNum21\t%d\t各个线程的玩家数目21\n" +
			
			// 各个线程的玩家数目 22
			"PlayerNum22\t%d\t各个线程的玩家数目22\n" +
			
			// 各个线程的玩家数目 23
			"PlayerNum23\t%d\t各个线程的玩家数目23\n" +
			
			// 各个线程的玩家数目 24
			"PlayerNum24\t%d\t各个线程的玩家数目24\n" +
			
			// 各个线程的玩家数目 25
			"PlayerNum25\t%d\t各个线程的玩家数目25\n" +
			
			// 各个线程的玩家数目 26
			"PlayerNum26\t%d\t各个线程的玩家数目26\n" +
			
			// 各个线程的玩家数目 27
			"PlayerNum27\t%d\t各个线程的玩家数目27\n" +
			
			// 各个线程的玩家数目 28
			"PlayerNum28\t%d\t各个线程的玩家数目28\n" +
			
			// 各个线程的玩家数目 29
			"PlayerNum29\t%d\t各个线程的玩家数目29\n" +
			
			// 各个线程的玩家数目 30
			"PlayerNum30\t%d\t各个线程的玩家数目30\n" +
			
			// 各个线程的玩家数目 31
			"PlayerNum31\t%d\t各个线程的玩家数目31\n" +
			
			// 各个线程的玩家数目 32
			"PlayerNum32\t%d\t各个线程的玩家数目32\n" +
			
			// 各个线程的玩家数目 33
			"PlayerNum33\t%d\t各个线程的玩家数目33\n" +
			
			// 各个线程的玩家数目 34
			"PlayerNum34\t%d\t各个线程的玩家数目34\n" +
			
			// 各个线程的玩家数目 35
			"PlayerNum35\t%d\t各个线程的玩家数目35\n" +
			
			// 各个线程的玩家数目 36
			"PlayerNum36\t%d\t各个线程的玩家数目36\n" +
			
			// 各个线程的玩家数目 37
			"PlayerNum37\t%d\t各个线程的玩家数目37\n" +
			
			// 各个线程的玩家数目 38
			"PlayerNum38\t%d\t各个线程的玩家数目38\n" +
			
			// 各个线程的玩家数目 39
			"PlayerNum39\t%d\t各个线程的玩家数目39\n" +
			
			// 各个线程的玩家数目 40
			"PlayerNum40\t%d\t各个线程的玩家数目40\n" +
			
			// 各个线程的玩家数目 41
			"PlayerNum41\t%d\t各个线程的玩家数目41\n" +
			
			// 各个线程的玩家数目 42
			"PlayerNum42\t%d\t各个线程的玩家数目42\n" +
			
			// 各个线程的玩家数目 43
			"PlayerNum43\t%d\t各个线程的玩家数目43\n" +
			
			// 各个线程的玩家数目 44
			"PlayerNum44\t%d\t各个线程的玩家数目44\n" +
			
			// 各个线程的玩家数目 45
			"PlayerNum45\t%d\t各个线程的玩家数目45\n" +
			
			// 各个线程的玩家数目 46
			"PlayerNum46\t%d\t各个线程的玩家数目46\n" +
			
			// 各个线程的玩家数目 47
			"PlayerNum47\t%d\t各个线程的玩家数目47\n" +
			
			// 各个线程的玩家数目 48
			"PlayerNum48\t%d\t各个线程的玩家数目48\n" +
			
			// 各个线程的玩家数目 49
			"PlayerNum49\t%d\t各个线程的玩家数目49\n" +
			
			// 各个线程的玩家数目 50
			"PlayerNum50\t%d\t各个线程的玩家数目50\n" +
			
			// 各个线程的玩家数目 51
			"PlayerNum51\t%d\t各个线程的玩家数目51\n" +
			
			// 各个线程的玩家数目 52
			"PlayerNum52\t%d\t各个线程的玩家数目52\n" +
			
			// 各个线程的玩家数目 53
			"PlayerNum53\t%d\t各个线程的玩家数目53\n" +
			
			// 各个线程的玩家数目 54
			"PlayerNum54\t%d\t各个线程的玩家数目54\n" +
			
			// 各个线程的玩家数目 55
			"PlayerNum55\t%d\t各个线程的玩家数目55\n" +
			
			// 各个线程的玩家数目 56
			"PlayerNum56\t%d\t各个线程的玩家数目56\n" +
			
			// 各个线程的玩家数目 57
			"PlayerNum57\t%d\t各个线程的玩家数目57\n" +
			
			// 各个线程的玩家数目 58
			"PlayerNum58\t%d\t各个线程的玩家数目58\n" +
			
			// 各个线程的玩家数目 59
			"PlayerNum59\t%d\t各个线程的玩家数目59\n" +
			
			// 各个线程的玩家数目 60
			"PlayerNum60\t%d\t各个线程的玩家数目60\n" +
			
			// 各个线程的玩家数目 61
			"PlayerNum61\t%d\t各个线程的玩家数目61\n" +
			
			// 各个线程的玩家数目 62
			"PlayerNum62\t%d\t各个线程的玩家数目62\n" +
			
			// 各个线程的玩家数目 63
			"PlayerNum63\t%d\t各个线程的玩家数目63\n" +
			
			// 各个线程的玩家数目 64
			"PlayerNum64\t%d\t各个线程的玩家数目64\n" +
			
			// 各个线程的玩家数目 65
			"PlayerNum65\t%d\t各个线程的玩家数目65\n" +
			
			// 各个线程的玩家数目 66
			"PlayerNum66\t%d\t各个线程的玩家数目66\n" +
			
			// 各个线程的玩家数目 67
			"PlayerNum67\t%d\t各个线程的玩家数目67\n" +
			
			// 各个线程的玩家数目 68
			"PlayerNum68\t%d\t各个线程的玩家数目68\n" +
			
			// 各个线程的玩家数目 69
			"PlayerNum69\t%d\t各个线程的玩家数目69\n" +
			
			// 各个线程的玩家数目 70
			"PlayerNum70\t%d\t各个线程的玩家数目70\n" +
			
			// 各个线程的玩家数目 71
			"PlayerNum71\t%d\t各个线程的玩家数目71\n" +
			
			// 各个线程的玩家数目 72
			"PlayerNum72\t%d\t各个线程的玩家数目72\n" +
			
			// 各个线程的玩家数目 73
			"PlayerNum73\t%d\t各个线程的玩家数目73\n" +
			
			// 各个线程的玩家数目 74
			"PlayerNum74\t%d\t各个线程的玩家数目74\n" +
			
			// 各个线程的玩家数目 75
			"PlayerNum75\t%d\t各个线程的玩家数目75\n" +
			
			// 各个线程的玩家数目 76
			"PlayerNum76\t%d\t各个线程的玩家数目76\n" +
			
			// 各个线程的玩家数目 77
			"PlayerNum77\t%d\t各个线程的玩家数目77\n" +
			
			// 各个线程的玩家数目 78
			"PlayerNum78\t%d\t各个线程的玩家数目78\n" +
			
			// 各个线程的玩家数目 79
			"PlayerNum79\t%d\t各个线程的玩家数目79\n" +
			
			// 各个线程的玩家数目 80
			"PlayerNum80\t%d\t各个线程的玩家数目80\n" +
			
			// 各个线程的玩家数目 81
			"PlayerNum81\t%d\t各个线程的玩家数目81\n" +
			
			// 各个线程的玩家数目 82
			"PlayerNum82\t%d\t各个线程的玩家数目82\n" +
			
			// 各个线程的玩家数目 83
			"PlayerNum83\t%d\t各个线程的玩家数目83\n" +
			
			// 各个线程的玩家数目 84
			"PlayerNum84\t%d\t各个线程的玩家数目84\n" +
			
			// 各个线程的玩家数目 85
			"PlayerNum85\t%d\t各个线程的玩家数目85\n" +
			
			// 各个线程的玩家数目 86
			"PlayerNum86\t%d\t各个线程的玩家数目86\n" +
			
			// 各个线程的玩家数目 87
			"PlayerNum87\t%d\t各个线程的玩家数目87\n" +
			
			// 各个线程的玩家数目 88
			"PlayerNum88\t%d\t各个线程的玩家数目88\n" +
			
			// 各个线程的玩家数目 89
			"PlayerNum89\t%d\t各个线程的玩家数目89\n" +
			
			// 各个线程的玩家数目 90
			"PlayerNum90\t%d\t各个线程的玩家数目90\n" +
			
			// 各个线程的玩家数目 91
			"PlayerNum91\t%d\t各个线程的玩家数目91\n" +
			
			// 各个线程的玩家数目 92
			"PlayerNum92\t%d\t各个线程的玩家数目92\n" +
			
			// 各个线程的玩家数目 93
			"PlayerNum93\t%d\t各个线程的玩家数目93\n" +
			
			// 各个线程的玩家数目 94
			"PlayerNum94\t%d\t各个线程的玩家数目94\n" +
			
			// 各个线程的玩家数目 95
			"PlayerNum95\t%d\t各个线程的玩家数目95\n" +
			
			// 各个线程的玩家数目 96
			"PlayerNum96\t%d\t各个线程的玩家数目96\n" +
			
			// 各个线程的玩家数目 97
			"PlayerNum97\t%d\t各个线程的玩家数目97\n" +
			
			// 各个线程的玩家数目 98
			"PlayerNum98\t%d\t各个线程的玩家数目98\n" +
			
			// 各个线程的玩家数目 99
			"PlayerNum99\t%d\t各个线程的玩家数目99\n" +
			
			
			
			// 各个线程的fps数目 0
			"FPS0\t%d\t各个线程的fps数目0\n" +
			
			// 各个线程的fps数目 1
			"FPS1\t%d\t各个线程的fps数目1\n" +
			
			// 各个线程的fps数目 2
			"FPS2\t%d\t各个线程的fps数目2\n" +
			
			// 各个线程的fps数目 3
			"FPS3\t%d\t各个线程的fps数目3\n" +
			
			// 各个线程的fps数目 4
			"FPS4\t%d\t各个线程的fps数目4\n" +
			
			// 各个线程的fps数目 5
			"FPS5\t%d\t各个线程的fps数目5\n" +
			
			// 各个线程的fps数目 6
			"FPS6\t%d\t各个线程的fps数目6\n" +
			
			// 各个线程的fps数目 7
			"FPS7\t%d\t各个线程的fps数目7\n" +
			
			// 各个线程的fps数目 8
			"FPS8\t%d\t各个线程的fps数目8\n" +
			
			// 各个线程的fps数目 9
			"FPS9\t%d\t各个线程的fps数目9\n" +
			
			// 各个线程的fps数目 10
			"FPS10\t%d\t各个线程的fps数目10\n" +
			
			// 各个线程的fps数目 11
			"FPS11\t%d\t各个线程的fps数目11\n" +
			
			// 各个线程的fps数目 12
			"FPS12\t%d\t各个线程的fps数目12\n" +
			
			// 各个线程的fps数目 13
			"FPS13\t%d\t各个线程的fps数目13\n" +
			
			// 各个线程的fps数目 14
			"FPS14\t%d\t各个线程的fps数目14\n" +
			
			// 各个线程的fps数目 15
			"FPS15\t%d\t各个线程的fps数目15\n" +
			
			// 各个线程的fps数目 16
			"FPS16\t%d\t各个线程的fps数目16\n" +
			
			// 各个线程的fps数目 17
			"FPS17\t%d\t各个线程的fps数目17\n" +
			
			// 各个线程的fps数目 18
			"FPS18\t%d\t各个线程的fps数目18\n" +
			
			// 各个线程的fps数目 19
			"FPS19\t%d\t各个线程的fps数目19\n" +
			
			// 各个线程的fps数目 20
			"FPS20\t%d\t各个线程的fps数目20\n" +
			
			// 各个线程的fps数目 21
			"FPS21\t%d\t各个线程的fps数目21\n" +
			
			// 各个线程的fps数目 22
			"FPS22\t%d\t各个线程的fps数目22\n" +
			
			// 各个线程的fps数目 23
			"FPS23\t%d\t各个线程的fps数目23\n" +
			
			// 各个线程的fps数目 24
			"FPS24\t%d\t各个线程的fps数目24\n" +
			
			// 各个线程的fps数目 25
			"FPS25\t%d\t各个线程的fps数目25\n" +
			
			// 各个线程的fps数目 26
			"FPS26\t%d\t各个线程的fps数目26\n" +
			
			// 各个线程的fps数目 27
			"FPS27\t%d\t各个线程的fps数目27\n" +
			
			// 各个线程的fps数目 28
			"FPS28\t%d\t各个线程的fps数目28\n" +
			
			// 各个线程的fps数目 29
			"FPS29\t%d\t各个线程的fps数目29\n" +
			
			// 各个线程的fps数目 30
			"FPS30\t%d\t各个线程的fps数目30\n" +
			
			// 各个线程的fps数目 31
			"FPS31\t%d\t各个线程的fps数目31\n" +
			
			// 各个线程的fps数目 32
			"FPS32\t%d\t各个线程的fps数目32\n" +
			
			// 各个线程的fps数目 33
			"FPS33\t%d\t各个线程的fps数目33\n" +
			
			// 各个线程的fps数目 34
			"FPS34\t%d\t各个线程的fps数目34\n" +
			
			// 各个线程的fps数目 35
			"FPS35\t%d\t各个线程的fps数目35\n" +
			
			// 各个线程的fps数目 36
			"FPS36\t%d\t各个线程的fps数目36\n" +
			
			// 各个线程的fps数目 37
			"FPS37\t%d\t各个线程的fps数目37\n" +
			
			// 各个线程的fps数目 38
			"FPS38\t%d\t各个线程的fps数目38\n" +
			
			// 各个线程的fps数目 39
			"FPS39\t%d\t各个线程的fps数目39\n" +
			
			// 各个线程的fps数目 40
			"FPS40\t%d\t各个线程的fps数目40\n" +
			
			// 各个线程的fps数目 41
			"FPS41\t%d\t各个线程的fps数目41\n" +
			
			// 各个线程的fps数目 42
			"FPS42\t%d\t各个线程的fps数目42\n" +
			
			// 各个线程的fps数目 43
			"FPS43\t%d\t各个线程的fps数目43\n" +
			
			// 各个线程的fps数目 44
			"FPS44\t%d\t各个线程的fps数目44\n" +
			
			// 各个线程的fps数目 45
			"FPS45\t%d\t各个线程的fps数目45\n" +
			
			// 各个线程的fps数目 46
			"FPS46\t%d\t各个线程的fps数目46\n" +
			
			// 各个线程的fps数目 47
			"FPS47\t%d\t各个线程的fps数目47\n" +
			
			// 各个线程的fps数目 48
			"FPS48\t%d\t各个线程的fps数目48\n" +
			
			// 各个线程的fps数目 49
			"FPS49\t%d\t各个线程的fps数目49\n" +
			
			// 各个线程的fps数目 50
			"FPS50\t%d\t各个线程的fps数目50\n" +
			
			// 各个线程的fps数目 51
			"FPS51\t%d\t各个线程的fps数目51\n" +
			
			// 各个线程的fps数目 52
			"FPS52\t%d\t各个线程的fps数目52\n" +
			
			// 各个线程的fps数目 53
			"FPS53\t%d\t各个线程的fps数目53\n" +
			
			// 各个线程的fps数目 54
			"FPS54\t%d\t各个线程的fps数目54\n" +
			
			// 各个线程的fps数目 55
			"FPS55\t%d\t各个线程的fps数目55\n" +
			
			// 各个线程的fps数目 56
			"FPS56\t%d\t各个线程的fps数目56\n" +
			
			// 各个线程的fps数目 57
			"FPS57\t%d\t各个线程的fps数目57\n" +
			
			// 各个线程的fps数目 58
			"FPS58\t%d\t各个线程的fps数目58\n" +
			
			// 各个线程的fps数目 59
			"FPS59\t%d\t各个线程的fps数目59\n" +
			
			// 各个线程的fps数目 60
			"FPS60\t%d\t各个线程的fps数目60\n" +
			
			// 各个线程的fps数目 61
			"FPS61\t%d\t各个线程的fps数目61\n" +
			
			// 各个线程的fps数目 62
			"FPS62\t%d\t各个线程的fps数目62\n" +
			
			// 各个线程的fps数目 63
			"FPS63\t%d\t各个线程的fps数目63\n" +
			
			// 各个线程的fps数目 64
			"FPS64\t%d\t各个线程的fps数目64\n" +
			
			// 各个线程的fps数目 65
			"FPS65\t%d\t各个线程的fps数目65\n" +
			
			// 各个线程的fps数目 66
			"FPS66\t%d\t各个线程的fps数目66\n" +
			
			// 各个线程的fps数目 67
			"FPS67\t%d\t各个线程的fps数目67\n" +
			
			// 各个线程的fps数目 68
			"FPS68\t%d\t各个线程的fps数目68\n" +
			
			// 各个线程的fps数目 69
			"FPS69\t%d\t各个线程的fps数目69\n" +
			
			// 各个线程的fps数目 70
			"FPS70\t%d\t各个线程的fps数目70\n" +
			
			// 各个线程的fps数目 71
			"FPS71\t%d\t各个线程的fps数目71\n" +
			
			// 各个线程的fps数目 72
			"FPS72\t%d\t各个线程的fps数目72\n" +
			
			// 各个线程的fps数目 73
			"FPS73\t%d\t各个线程的fps数目73\n" +
			
			// 各个线程的fps数目 74
			"FPS74\t%d\t各个线程的fps数目74\n" +
			
			// 各个线程的fps数目 75
			"FPS75\t%d\t各个线程的fps数目75\n" +
			
			// 各个线程的fps数目 76
			"FPS76\t%d\t各个线程的fps数目76\n" +
			
			// 各个线程的fps数目 77
			"FPS77\t%d\t各个线程的fps数目77\n" +
			
			// 各个线程的fps数目 78
			"FPS78\t%d\t各个线程的fps数目78\n" +
			
			// 各个线程的fps数目 79
			"FPS79\t%d\t各个线程的fps数目79\n" +
			
			// 各个线程的fps数目 80
			"FPS80\t%d\t各个线程的fps数目80\n" +
			
			// 各个线程的fps数目 81
			"FPS81\t%d\t各个线程的fps数目81\n" +
			
			// 各个线程的fps数目 82
			"FPS82\t%d\t各个线程的fps数目82\n" +
			
			// 各个线程的fps数目 83
			"FPS83\t%d\t各个线程的fps数目83\n" +
			
			// 各个线程的fps数目 84
			"FPS84\t%d\t各个线程的fps数目84\n" +
			
			// 各个线程的fps数目 85
			"FPS85\t%d\t各个线程的fps数目85\n" +
			
			// 各个线程的fps数目 86
			"FPS86\t%d\t各个线程的fps数目86\n" +
			
			// 各个线程的fps数目 87
			"FPS87\t%d\t各个线程的fps数目87\n" +
			
			// 各个线程的fps数目 88
			"FPS88\t%d\t各个线程的fps数目88\n" +
			
			// 各个线程的fps数目 89
			"FPS89\t%d\t各个线程的fps数目89\n" +
			
			// 各个线程的fps数目 90
			"FPS90\t%d\t各个线程的fps数目90\n" +
			
			// 各个线程的fps数目 91
			"FPS91\t%d\t各个线程的fps数目91\n" +
			
			// 各个线程的fps数目 92
			"FPS92\t%d\t各个线程的fps数目92\n" +
			
			// 各个线程的fps数目 93
			"FPS93\t%d\t各个线程的fps数目93\n" +
			
			// 各个线程的fps数目 94
			"FPS94\t%d\t各个线程的fps数目94\n" +
			
			// 各个线程的fps数目 95
			"FPS95\t%d\t各个线程的fps数目95\n" +
			
			// 各个线程的fps数目 96
			"FPS96\t%d\t各个线程的fps数目96\n" +
			
			// 各个线程的fps数目 97
			"FPS97\t%d\t各个线程的fps数目97\n" +
			
			// 各个线程的fps数目 98
			"FPS98\t%d\t各个线程的fps数目98\n" +
			
			// 各个线程的fps数目 99
			"FPS99\t%d\t各个线程的fps数目99\n" +
			
			
			
			// 桌子各状态数目 0
			"RoutineStateNum0\t%d\t桌子各状态数目0\n" +
			
			// 桌子各状态数目 1
			"RoutineStateNum1\t%d\t桌子各状态数目1\n" +
			
			// 桌子各状态数目 2
			"RoutineStateNum2\t%d\t桌子各状态数目2\n" +
			
			// 桌子各状态数目 3
			"RoutineStateNum3\t%d\t桌子各状态数目3\n" +
			
			// 桌子各状态数目 4
			"RoutineStateNum4\t%d\t桌子各状态数目4\n" +
			
			// 桌子各状态数目 5
			"RoutineStateNum5\t%d\t桌子各状态数目5\n" +
			
			// 桌子各状态数目 6
			"RoutineStateNum6\t%d\t桌子各状态数目6\n" +
			
			// 桌子各状态数目 7
			"RoutineStateNum7\t%d\t桌子各状态数目7\n" +
			
			// 桌子各状态数目 8
			"RoutineStateNum8\t%d\t桌子各状态数目8\n" +
			
			// 桌子各状态数目 9
			"RoutineStateNum9\t%d\t桌子各状态数目9\n" +
			
			// 桌子各状态数目 10
			"RoutineStateNum10\t%d\t桌子各状态数目10\n" +
			
			
			
			
			// Top收包数目 0
			"TopRecvPacketNumId0\t%d\tTop收包数目Id0\nTopRecvPacketNumVal0\t%d\tTop收包数目Val0\n" +
			
			// Top收包数目 1
			"TopRecvPacketNumId1\t%d\tTop收包数目Id1\nTopRecvPacketNumVal1\t%d\tTop收包数目Val1\n" +
			
			// Top收包数目 2
			"TopRecvPacketNumId2\t%d\tTop收包数目Id2\nTopRecvPacketNumVal2\t%d\tTop收包数目Val2\n" +
			
			// Top收包数目 3
			"TopRecvPacketNumId3\t%d\tTop收包数目Id3\nTopRecvPacketNumVal3\t%d\tTop收包数目Val3\n" +
			
			// Top收包数目 4
			"TopRecvPacketNumId4\t%d\tTop收包数目Id4\nTopRecvPacketNumVal4\t%d\tTop收包数目Val4\n" +
			
			
			
			// Top发包数目 0
			"TopSendPacketNumId0\t%d\tTop发包数目Id0\nTopSendPacketNumVal0\t%d\tTop发包数目Val0\n" +
			
			// Top发包数目 1
			"TopSendPacketNumId1\t%d\tTop发包数目Id1\nTopSendPacketNumVal1\t%d\tTop发包数目Val1\n" +
			
			// Top发包数目 2
			"TopSendPacketNumId2\t%d\tTop发包数目Id2\nTopSendPacketNumVal2\t%d\tTop发包数目Val2\n" +
			
			// Top发包数目 3
			"TopSendPacketNumId3\t%d\tTop发包数目Id3\nTopSendPacketNumVal3\t%d\tTop发包数目Val3\n" +
			
			// Top发包数目 4
			"TopSendPacketNumId4\t%d\tTop发包数目Id4\nTopSendPacketNumVal4\t%d\tTop发包数目Val4\n" +
			
			
			
			// Top收包流量 0
			"TopRecvSizeNumId0\t%d\tTop收包流量Id0\nTopRecvSizeNumVal0\t%d\tTop收包流量Val0\n" +
			
			// Top收包流量 1
			"TopRecvSizeNumId1\t%d\tTop收包流量Id1\nTopRecvSizeNumVal1\t%d\tTop收包流量Val1\n" +
			
			// Top收包流量 2
			"TopRecvSizeNumId2\t%d\tTop收包流量Id2\nTopRecvSizeNumVal2\t%d\tTop收包流量Val2\n" +
			
			// Top收包流量 3
			"TopRecvSizeNumId3\t%d\tTop收包流量Id3\nTopRecvSizeNumVal3\t%d\tTop收包流量Val3\n" +
			
			// Top收包流量 4
			"TopRecvSizeNumId4\t%d\tTop收包流量Id4\nTopRecvSizeNumVal4\t%d\tTop收包流量Val4\n" +
			
			
			
			// Top发包流量 0
			"TopSendSizeNumId0\t%d\tTop发包流量Id0\nTopSendSizeNumVal0\t%d\tTop发包流量Val0\n" +
			
			// Top发包流量 1
			"TopSendSizeNumId1\t%d\tTop发包流量Id1\nTopSendSizeNumVal1\t%d\tTop发包流量Val1\n" +
			
			// Top发包流量 2
			"TopSendSizeNumId2\t%d\tTop发包流量Id2\nTopSendSizeNumVal2\t%d\tTop发包流量Val2\n" +
			
			// Top发包流量 3
			"TopSendSizeNumId3\t%d\tTop发包流量Id3\nTopSendSizeNumVal3\t%d\tTop发包流量Val3\n" +
			
			// Top发包流量 4
			"TopSendSizeNumId4\t%d\tTop发包流量Id4\nTopSendSizeNumVal4\t%d\tTop发包流量Val4\n" +
			
			
			
			// Top收包处理时间 0
			"TopProcessTimeId0\t%d\tTop收包处理时间Id0\nTopProcessTimeVal0\t%d\tTop收包处理时间Val0\n" +
			
			// Top收包处理时间 1
			"TopProcessTimeId1\t%d\tTop收包处理时间Id1\nTopProcessTimeVal1\t%d\tTop收包处理时间Val1\n" +
			
			// Top收包处理时间 2
			"TopProcessTimeId2\t%d\tTop收包处理时间Id2\nTopProcessTimeVal2\t%d\tTop收包处理时间Val2\n" +
			
			// Top收包处理时间 3
			"TopProcessTimeId3\t%d\tTop收包处理时间Id3\nTopProcessTimeVal3\t%d\tTop收包处理时间Val3\n" +
			
			// Top收包处理时间 4
			"TopProcessTimeId4\t%d\tTop收包处理时间Id4\nTopProcessTimeVal4\t%d\tTop收包处理时间Val4\n" +
			
			
			
			"\n"
			
			, time
			
			// 桌子数目
			, TotalTableNum
			
			// 桌子上的玩家数目
			, TotalPlayerNum
			
			// fps数目
			, TotalFPS
			
			// 开局的桌子
			, NewTableNum
			
			// 结算的桌子
			, DestroyTableNum
			
			// 异常的桌子
			, ExceptionTableNum
			
			// 收包数目
			, RecvPacketNum
			
			// 发包数目
			, SendPacketNum
			
			// 收包流量
			, RecvSizeNum
			
			// 发包流量
			, SendSizeNum
			
			// Top收包处理时间
			, ProcessTime
			
			
			
			// 各个线程的桌子数目 0
			, TableNum[0]
			
			// 各个线程的桌子数目 1
			, TableNum[1]
			
			// 各个线程的桌子数目 2
			, TableNum[2]
			
			// 各个线程的桌子数目 3
			, TableNum[3]
			
			// 各个线程的桌子数目 4
			, TableNum[4]
			
			// 各个线程的桌子数目 5
			, TableNum[5]
			
			// 各个线程的桌子数目 6
			, TableNum[6]
			
			// 各个线程的桌子数目 7
			, TableNum[7]
			
			// 各个线程的桌子数目 8
			, TableNum[8]
			
			// 各个线程的桌子数目 9
			, TableNum[9]
			
			// 各个线程的桌子数目 10
			, TableNum[10]
			
			// 各个线程的桌子数目 11
			, TableNum[11]
			
			// 各个线程的桌子数目 12
			, TableNum[12]
			
			// 各个线程的桌子数目 13
			, TableNum[13]
			
			// 各个线程的桌子数目 14
			, TableNum[14]
			
			// 各个线程的桌子数目 15
			, TableNum[15]
			
			// 各个线程的桌子数目 16
			, TableNum[16]
			
			// 各个线程的桌子数目 17
			, TableNum[17]
			
			// 各个线程的桌子数目 18
			, TableNum[18]
			
			// 各个线程的桌子数目 19
			, TableNum[19]
			
			// 各个线程的桌子数目 20
			, TableNum[20]
			
			// 各个线程的桌子数目 21
			, TableNum[21]
			
			// 各个线程的桌子数目 22
			, TableNum[22]
			
			// 各个线程的桌子数目 23
			, TableNum[23]
			
			// 各个线程的桌子数目 24
			, TableNum[24]
			
			// 各个线程的桌子数目 25
			, TableNum[25]
			
			// 各个线程的桌子数目 26
			, TableNum[26]
			
			// 各个线程的桌子数目 27
			, TableNum[27]
			
			// 各个线程的桌子数目 28
			, TableNum[28]
			
			// 各个线程的桌子数目 29
			, TableNum[29]
			
			// 各个线程的桌子数目 30
			, TableNum[30]
			
			// 各个线程的桌子数目 31
			, TableNum[31]
			
			// 各个线程的桌子数目 32
			, TableNum[32]
			
			// 各个线程的桌子数目 33
			, TableNum[33]
			
			// 各个线程的桌子数目 34
			, TableNum[34]
			
			// 各个线程的桌子数目 35
			, TableNum[35]
			
			// 各个线程的桌子数目 36
			, TableNum[36]
			
			// 各个线程的桌子数目 37
			, TableNum[37]
			
			// 各个线程的桌子数目 38
			, TableNum[38]
			
			// 各个线程的桌子数目 39
			, TableNum[39]
			
			// 各个线程的桌子数目 40
			, TableNum[40]
			
			// 各个线程的桌子数目 41
			, TableNum[41]
			
			// 各个线程的桌子数目 42
			, TableNum[42]
			
			// 各个线程的桌子数目 43
			, TableNum[43]
			
			// 各个线程的桌子数目 44
			, TableNum[44]
			
			// 各个线程的桌子数目 45
			, TableNum[45]
			
			// 各个线程的桌子数目 46
			, TableNum[46]
			
			// 各个线程的桌子数目 47
			, TableNum[47]
			
			// 各个线程的桌子数目 48
			, TableNum[48]
			
			// 各个线程的桌子数目 49
			, TableNum[49]
			
			// 各个线程的桌子数目 50
			, TableNum[50]
			
			// 各个线程的桌子数目 51
			, TableNum[51]
			
			// 各个线程的桌子数目 52
			, TableNum[52]
			
			// 各个线程的桌子数目 53
			, TableNum[53]
			
			// 各个线程的桌子数目 54
			, TableNum[54]
			
			// 各个线程的桌子数目 55
			, TableNum[55]
			
			// 各个线程的桌子数目 56
			, TableNum[56]
			
			// 各个线程的桌子数目 57
			, TableNum[57]
			
			// 各个线程的桌子数目 58
			, TableNum[58]
			
			// 各个线程的桌子数目 59
			, TableNum[59]
			
			// 各个线程的桌子数目 60
			, TableNum[60]
			
			// 各个线程的桌子数目 61
			, TableNum[61]
			
			// 各个线程的桌子数目 62
			, TableNum[62]
			
			// 各个线程的桌子数目 63
			, TableNum[63]
			
			// 各个线程的桌子数目 64
			, TableNum[64]
			
			// 各个线程的桌子数目 65
			, TableNum[65]
			
			// 各个线程的桌子数目 66
			, TableNum[66]
			
			// 各个线程的桌子数目 67
			, TableNum[67]
			
			// 各个线程的桌子数目 68
			, TableNum[68]
			
			// 各个线程的桌子数目 69
			, TableNum[69]
			
			// 各个线程的桌子数目 70
			, TableNum[70]
			
			// 各个线程的桌子数目 71
			, TableNum[71]
			
			// 各个线程的桌子数目 72
			, TableNum[72]
			
			// 各个线程的桌子数目 73
			, TableNum[73]
			
			// 各个线程的桌子数目 74
			, TableNum[74]
			
			// 各个线程的桌子数目 75
			, TableNum[75]
			
			// 各个线程的桌子数目 76
			, TableNum[76]
			
			// 各个线程的桌子数目 77
			, TableNum[77]
			
			// 各个线程的桌子数目 78
			, TableNum[78]
			
			// 各个线程的桌子数目 79
			, TableNum[79]
			
			// 各个线程的桌子数目 80
			, TableNum[80]
			
			// 各个线程的桌子数目 81
			, TableNum[81]
			
			// 各个线程的桌子数目 82
			, TableNum[82]
			
			// 各个线程的桌子数目 83
			, TableNum[83]
			
			// 各个线程的桌子数目 84
			, TableNum[84]
			
			// 各个线程的桌子数目 85
			, TableNum[85]
			
			// 各个线程的桌子数目 86
			, TableNum[86]
			
			// 各个线程的桌子数目 87
			, TableNum[87]
			
			// 各个线程的桌子数目 88
			, TableNum[88]
			
			// 各个线程的桌子数目 89
			, TableNum[89]
			
			// 各个线程的桌子数目 90
			, TableNum[90]
			
			// 各个线程的桌子数目 91
			, TableNum[91]
			
			// 各个线程的桌子数目 92
			, TableNum[92]
			
			// 各个线程的桌子数目 93
			, TableNum[93]
			
			// 各个线程的桌子数目 94
			, TableNum[94]
			
			// 各个线程的桌子数目 95
			, TableNum[95]
			
			// 各个线程的桌子数目 96
			, TableNum[96]
			
			// 各个线程的桌子数目 97
			, TableNum[97]
			
			// 各个线程的桌子数目 98
			, TableNum[98]
			
			// 各个线程的桌子数目 99
			, TableNum[99]
			
			
			
			// 各个房间的桌子数目 0
			, RoomTableNum[0]
			
			// 各个房间的桌子数目 1
			, RoomTableNum[1]
			
			// 各个房间的桌子数目 2
			, RoomTableNum[2]
			
			
			
			// 各个线程的玩家数目 0
			, PlayerNum[0]
			
			// 各个线程的玩家数目 1
			, PlayerNum[1]
			
			// 各个线程的玩家数目 2
			, PlayerNum[2]
			
			// 各个线程的玩家数目 3
			, PlayerNum[3]
			
			// 各个线程的玩家数目 4
			, PlayerNum[4]
			
			// 各个线程的玩家数目 5
			, PlayerNum[5]
			
			// 各个线程的玩家数目 6
			, PlayerNum[6]
			
			// 各个线程的玩家数目 7
			, PlayerNum[7]
			
			// 各个线程的玩家数目 8
			, PlayerNum[8]
			
			// 各个线程的玩家数目 9
			, PlayerNum[9]
			
			// 各个线程的玩家数目 10
			, PlayerNum[10]
			
			// 各个线程的玩家数目 11
			, PlayerNum[11]
			
			// 各个线程的玩家数目 12
			, PlayerNum[12]
			
			// 各个线程的玩家数目 13
			, PlayerNum[13]
			
			// 各个线程的玩家数目 14
			, PlayerNum[14]
			
			// 各个线程的玩家数目 15
			, PlayerNum[15]
			
			// 各个线程的玩家数目 16
			, PlayerNum[16]
			
			// 各个线程的玩家数目 17
			, PlayerNum[17]
			
			// 各个线程的玩家数目 18
			, PlayerNum[18]
			
			// 各个线程的玩家数目 19
			, PlayerNum[19]
			
			// 各个线程的玩家数目 20
			, PlayerNum[20]
			
			// 各个线程的玩家数目 21
			, PlayerNum[21]
			
			// 各个线程的玩家数目 22
			, PlayerNum[22]
			
			// 各个线程的玩家数目 23
			, PlayerNum[23]
			
			// 各个线程的玩家数目 24
			, PlayerNum[24]
			
			// 各个线程的玩家数目 25
			, PlayerNum[25]
			
			// 各个线程的玩家数目 26
			, PlayerNum[26]
			
			// 各个线程的玩家数目 27
			, PlayerNum[27]
			
			// 各个线程的玩家数目 28
			, PlayerNum[28]
			
			// 各个线程的玩家数目 29
			, PlayerNum[29]
			
			// 各个线程的玩家数目 30
			, PlayerNum[30]
			
			// 各个线程的玩家数目 31
			, PlayerNum[31]
			
			// 各个线程的玩家数目 32
			, PlayerNum[32]
			
			// 各个线程的玩家数目 33
			, PlayerNum[33]
			
			// 各个线程的玩家数目 34
			, PlayerNum[34]
			
			// 各个线程的玩家数目 35
			, PlayerNum[35]
			
			// 各个线程的玩家数目 36
			, PlayerNum[36]
			
			// 各个线程的玩家数目 37
			, PlayerNum[37]
			
			// 各个线程的玩家数目 38
			, PlayerNum[38]
			
			// 各个线程的玩家数目 39
			, PlayerNum[39]
			
			// 各个线程的玩家数目 40
			, PlayerNum[40]
			
			// 各个线程的玩家数目 41
			, PlayerNum[41]
			
			// 各个线程的玩家数目 42
			, PlayerNum[42]
			
			// 各个线程的玩家数目 43
			, PlayerNum[43]
			
			// 各个线程的玩家数目 44
			, PlayerNum[44]
			
			// 各个线程的玩家数目 45
			, PlayerNum[45]
			
			// 各个线程的玩家数目 46
			, PlayerNum[46]
			
			// 各个线程的玩家数目 47
			, PlayerNum[47]
			
			// 各个线程的玩家数目 48
			, PlayerNum[48]
			
			// 各个线程的玩家数目 49
			, PlayerNum[49]
			
			// 各个线程的玩家数目 50
			, PlayerNum[50]
			
			// 各个线程的玩家数目 51
			, PlayerNum[51]
			
			// 各个线程的玩家数目 52
			, PlayerNum[52]
			
			// 各个线程的玩家数目 53
			, PlayerNum[53]
			
			// 各个线程的玩家数目 54
			, PlayerNum[54]
			
			// 各个线程的玩家数目 55
			, PlayerNum[55]
			
			// 各个线程的玩家数目 56
			, PlayerNum[56]
			
			// 各个线程的玩家数目 57
			, PlayerNum[57]
			
			// 各个线程的玩家数目 58
			, PlayerNum[58]
			
			// 各个线程的玩家数目 59
			, PlayerNum[59]
			
			// 各个线程的玩家数目 60
			, PlayerNum[60]
			
			// 各个线程的玩家数目 61
			, PlayerNum[61]
			
			// 各个线程的玩家数目 62
			, PlayerNum[62]
			
			// 各个线程的玩家数目 63
			, PlayerNum[63]
			
			// 各个线程的玩家数目 64
			, PlayerNum[64]
			
			// 各个线程的玩家数目 65
			, PlayerNum[65]
			
			// 各个线程的玩家数目 66
			, PlayerNum[66]
			
			// 各个线程的玩家数目 67
			, PlayerNum[67]
			
			// 各个线程的玩家数目 68
			, PlayerNum[68]
			
			// 各个线程的玩家数目 69
			, PlayerNum[69]
			
			// 各个线程的玩家数目 70
			, PlayerNum[70]
			
			// 各个线程的玩家数目 71
			, PlayerNum[71]
			
			// 各个线程的玩家数目 72
			, PlayerNum[72]
			
			// 各个线程的玩家数目 73
			, PlayerNum[73]
			
			// 各个线程的玩家数目 74
			, PlayerNum[74]
			
			// 各个线程的玩家数目 75
			, PlayerNum[75]
			
			// 各个线程的玩家数目 76
			, PlayerNum[76]
			
			// 各个线程的玩家数目 77
			, PlayerNum[77]
			
			// 各个线程的玩家数目 78
			, PlayerNum[78]
			
			// 各个线程的玩家数目 79
			, PlayerNum[79]
			
			// 各个线程的玩家数目 80
			, PlayerNum[80]
			
			// 各个线程的玩家数目 81
			, PlayerNum[81]
			
			// 各个线程的玩家数目 82
			, PlayerNum[82]
			
			// 各个线程的玩家数目 83
			, PlayerNum[83]
			
			// 各个线程的玩家数目 84
			, PlayerNum[84]
			
			// 各个线程的玩家数目 85
			, PlayerNum[85]
			
			// 各个线程的玩家数目 86
			, PlayerNum[86]
			
			// 各个线程的玩家数目 87
			, PlayerNum[87]
			
			// 各个线程的玩家数目 88
			, PlayerNum[88]
			
			// 各个线程的玩家数目 89
			, PlayerNum[89]
			
			// 各个线程的玩家数目 90
			, PlayerNum[90]
			
			// 各个线程的玩家数目 91
			, PlayerNum[91]
			
			// 各个线程的玩家数目 92
			, PlayerNum[92]
			
			// 各个线程的玩家数目 93
			, PlayerNum[93]
			
			// 各个线程的玩家数目 94
			, PlayerNum[94]
			
			// 各个线程的玩家数目 95
			, PlayerNum[95]
			
			// 各个线程的玩家数目 96
			, PlayerNum[96]
			
			// 各个线程的玩家数目 97
			, PlayerNum[97]
			
			// 各个线程的玩家数目 98
			, PlayerNum[98]
			
			// 各个线程的玩家数目 99
			, PlayerNum[99]
			
			
			
			// 各个线程的fps数目 0
			, FPS[0]
			
			// 各个线程的fps数目 1
			, FPS[1]
			
			// 各个线程的fps数目 2
			, FPS[2]
			
			// 各个线程的fps数目 3
			, FPS[3]
			
			// 各个线程的fps数目 4
			, FPS[4]
			
			// 各个线程的fps数目 5
			, FPS[5]
			
			// 各个线程的fps数目 6
			, FPS[6]
			
			// 各个线程的fps数目 7
			, FPS[7]
			
			// 各个线程的fps数目 8
			, FPS[8]
			
			// 各个线程的fps数目 9
			, FPS[9]
			
			// 各个线程的fps数目 10
			, FPS[10]
			
			// 各个线程的fps数目 11
			, FPS[11]
			
			// 各个线程的fps数目 12
			, FPS[12]
			
			// 各个线程的fps数目 13
			, FPS[13]
			
			// 各个线程的fps数目 14
			, FPS[14]
			
			// 各个线程的fps数目 15
			, FPS[15]
			
			// 各个线程的fps数目 16
			, FPS[16]
			
			// 各个线程的fps数目 17
			, FPS[17]
			
			// 各个线程的fps数目 18
			, FPS[18]
			
			// 各个线程的fps数目 19
			, FPS[19]
			
			// 各个线程的fps数目 20
			, FPS[20]
			
			// 各个线程的fps数目 21
			, FPS[21]
			
			// 各个线程的fps数目 22
			, FPS[22]
			
			// 各个线程的fps数目 23
			, FPS[23]
			
			// 各个线程的fps数目 24
			, FPS[24]
			
			// 各个线程的fps数目 25
			, FPS[25]
			
			// 各个线程的fps数目 26
			, FPS[26]
			
			// 各个线程的fps数目 27
			, FPS[27]
			
			// 各个线程的fps数目 28
			, FPS[28]
			
			// 各个线程的fps数目 29
			, FPS[29]
			
			// 各个线程的fps数目 30
			, FPS[30]
			
			// 各个线程的fps数目 31
			, FPS[31]
			
			// 各个线程的fps数目 32
			, FPS[32]
			
			// 各个线程的fps数目 33
			, FPS[33]
			
			// 各个线程的fps数目 34
			, FPS[34]
			
			// 各个线程的fps数目 35
			, FPS[35]
			
			// 各个线程的fps数目 36
			, FPS[36]
			
			// 各个线程的fps数目 37
			, FPS[37]
			
			// 各个线程的fps数目 38
			, FPS[38]
			
			// 各个线程的fps数目 39
			, FPS[39]
			
			// 各个线程的fps数目 40
			, FPS[40]
			
			// 各个线程的fps数目 41
			, FPS[41]
			
			// 各个线程的fps数目 42
			, FPS[42]
			
			// 各个线程的fps数目 43
			, FPS[43]
			
			// 各个线程的fps数目 44
			, FPS[44]
			
			// 各个线程的fps数目 45
			, FPS[45]
			
			// 各个线程的fps数目 46
			, FPS[46]
			
			// 各个线程的fps数目 47
			, FPS[47]
			
			// 各个线程的fps数目 48
			, FPS[48]
			
			// 各个线程的fps数目 49
			, FPS[49]
			
			// 各个线程的fps数目 50
			, FPS[50]
			
			// 各个线程的fps数目 51
			, FPS[51]
			
			// 各个线程的fps数目 52
			, FPS[52]
			
			// 各个线程的fps数目 53
			, FPS[53]
			
			// 各个线程的fps数目 54
			, FPS[54]
			
			// 各个线程的fps数目 55
			, FPS[55]
			
			// 各个线程的fps数目 56
			, FPS[56]
			
			// 各个线程的fps数目 57
			, FPS[57]
			
			// 各个线程的fps数目 58
			, FPS[58]
			
			// 各个线程的fps数目 59
			, FPS[59]
			
			// 各个线程的fps数目 60
			, FPS[60]
			
			// 各个线程的fps数目 61
			, FPS[61]
			
			// 各个线程的fps数目 62
			, FPS[62]
			
			// 各个线程的fps数目 63
			, FPS[63]
			
			// 各个线程的fps数目 64
			, FPS[64]
			
			// 各个线程的fps数目 65
			, FPS[65]
			
			// 各个线程的fps数目 66
			, FPS[66]
			
			// 各个线程的fps数目 67
			, FPS[67]
			
			// 各个线程的fps数目 68
			, FPS[68]
			
			// 各个线程的fps数目 69
			, FPS[69]
			
			// 各个线程的fps数目 70
			, FPS[70]
			
			// 各个线程的fps数目 71
			, FPS[71]
			
			// 各个线程的fps数目 72
			, FPS[72]
			
			// 各个线程的fps数目 73
			, FPS[73]
			
			// 各个线程的fps数目 74
			, FPS[74]
			
			// 各个线程的fps数目 75
			, FPS[75]
			
			// 各个线程的fps数目 76
			, FPS[76]
			
			// 各个线程的fps数目 77
			, FPS[77]
			
			// 各个线程的fps数目 78
			, FPS[78]
			
			// 各个线程的fps数目 79
			, FPS[79]
			
			// 各个线程的fps数目 80
			, FPS[80]
			
			// 各个线程的fps数目 81
			, FPS[81]
			
			// 各个线程的fps数目 82
			, FPS[82]
			
			// 各个线程的fps数目 83
			, FPS[83]
			
			// 各个线程的fps数目 84
			, FPS[84]
			
			// 各个线程的fps数目 85
			, FPS[85]
			
			// 各个线程的fps数目 86
			, FPS[86]
			
			// 各个线程的fps数目 87
			, FPS[87]
			
			// 各个线程的fps数目 88
			, FPS[88]
			
			// 各个线程的fps数目 89
			, FPS[89]
			
			// 各个线程的fps数目 90
			, FPS[90]
			
			// 各个线程的fps数目 91
			, FPS[91]
			
			// 各个线程的fps数目 92
			, FPS[92]
			
			// 各个线程的fps数目 93
			, FPS[93]
			
			// 各个线程的fps数目 94
			, FPS[94]
			
			// 各个线程的fps数目 95
			, FPS[95]
			
			// 各个线程的fps数目 96
			, FPS[96]
			
			// 各个线程的fps数目 97
			, FPS[97]
			
			// 各个线程的fps数目 98
			, FPS[98]
			
			// 各个线程的fps数目 99
			, FPS[99]
			
			
			
			// 桌子各状态数目 0
			, RoutineStateNum[0]
			
			// 桌子各状态数目 1
			, RoutineStateNum[1]
			
			// 桌子各状态数目 2
			, RoutineStateNum[2]
			
			// 桌子各状态数目 3
			, RoutineStateNum[3]
			
			// 桌子各状态数目 4
			, RoutineStateNum[4]
			
			// 桌子各状态数目 5
			, RoutineStateNum[5]
			
			// 桌子各状态数目 6
			, RoutineStateNum[6]
			
			// 桌子各状态数目 7
			, RoutineStateNum[7]
			
			// 桌子各状态数目 8
			, RoutineStateNum[8]
			
			// 桌子各状态数目 9
			, RoutineStateNum[9]
			
			// 桌子各状态数目 10
			, RoutineStateNum[10]
			
			
			
			
			// Top收包数目 0
			, uTopRecvPacketNumId[0], uTopRecvPacketNumVal[0]
			
			// Top收包数目 1
			, uTopRecvPacketNumId[1], uTopRecvPacketNumVal[1]
			
			// Top收包数目 2
			, uTopRecvPacketNumId[2], uTopRecvPacketNumVal[2]
			
			// Top收包数目 3
			, uTopRecvPacketNumId[3], uTopRecvPacketNumVal[3]
			
			// Top收包数目 4
			, uTopRecvPacketNumId[4], uTopRecvPacketNumVal[4]
			
			
			
			// Top发包数目 0
			, uTopSendPacketNumId[0], uTopSendPacketNumVal[0]
			
			// Top发包数目 1
			, uTopSendPacketNumId[1], uTopSendPacketNumVal[1]
			
			// Top发包数目 2
			, uTopSendPacketNumId[2], uTopSendPacketNumVal[2]
			
			// Top发包数目 3
			, uTopSendPacketNumId[3], uTopSendPacketNumVal[3]
			
			// Top发包数目 4
			, uTopSendPacketNumId[4], uTopSendPacketNumVal[4]
			
			
			
			// Top收包流量 0
			, uTopRecvSizeNumId[0], uTopRecvSizeNumVal[0]
			
			// Top收包流量 1
			, uTopRecvSizeNumId[1], uTopRecvSizeNumVal[1]
			
			// Top收包流量 2
			, uTopRecvSizeNumId[2], uTopRecvSizeNumVal[2]
			
			// Top收包流量 3
			, uTopRecvSizeNumId[3], uTopRecvSizeNumVal[3]
			
			// Top收包流量 4
			, uTopRecvSizeNumId[4], uTopRecvSizeNumVal[4]
			
			
			
			// Top发包流量 0
			, uTopSendSizeNumId[0], uTopSendSizeNumVal[0]
			
			// Top发包流量 1
			, uTopSendSizeNumId[1], uTopSendSizeNumVal[1]
			
			// Top发包流量 2
			, uTopSendSizeNumId[2], uTopSendSizeNumVal[2]
			
			// Top发包流量 3
			, uTopSendSizeNumId[3], uTopSendSizeNumVal[3]
			
			// Top发包流量 4
			, uTopSendSizeNumId[4], uTopSendSizeNumVal[4]
			
			
			
			// Top收包处理时间 0
			, uTopProcessTimeId[0], uTopProcessTimeVal[0]
			
			// Top收包处理时间 1
			, uTopProcessTimeId[1], uTopProcessTimeVal[1]
			
			// Top收包处理时间 2
			, uTopProcessTimeId[2], uTopProcessTimeVal[2]
			
			// Top收包处理时间 3
			, uTopProcessTimeId[3], uTopProcessTimeVal[3]
			
			// Top收包处理时间 4
			, uTopProcessTimeId[4], uTopProcessTimeVal[4]
			
			
			
			);
			
		clear();
		
		try
		{
			FileOutputStream out = new FileOutputStream(file, true);
			out.write(str.toString().getBytes("utf-8"));
			out.close();
		}
		catch (IOException e)
		{
			e.printStackTrace();
			return;
		}
		
	}
    
}

